### ISSUE TITLE
Please make a Safari/MacOS workflow and assign it to Dave.

### ISSUE THREAD

**Issue by basilgohar** [OSC/ondemand-testing#6]
Eric, please make a testplan for Safari on MacOS and assign it to Dave.  At least, if he is so inclined, he can do a little bit.

**Comment by dhudak-osc** [comment]
Yep.  Happy to do it.  -Dave
> On Jun 2, 2016, at 2:44 PM, Basil Mohamed Gohar <notifications@github.com> wrote:
> 
> Eric, please make a testplan for Safari on MacOS and assign it to Dave. At least, if he is so inclined, he can do a little bit.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
David E. Hudak, Ph.D.
Interim Executive Director and Director of Supercomputer Services
Ohio Supercomputer Center (OSC)
A member of the Ohio Technology Consortium
1224 Kinnear Road, Columbus, Ohio 43212
Office: (614) 247-8670 •  Fax: (614) 292-7168
dhudak@osc.edu

Learn more about OSC at https://osc.edu

**Comment by ericfranz** [comment]
Done!

**Comment by ericfranz** [comment]
@dhudak-osc also be aware that as we go through the test plans we are noticing typos or lines that don't make sense we are updating the test plan accordingly so when we assign to the students they have the updated version
