### ISSUE TITLE
Safari 9.1 OS X - OD3.0

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-testing#7]
#### For all steps, note application behavior that seems odd or unexpected.

- [x] Ability to access dashboard via https://websvcs08.osc.edu/pun/sys/dashboard
- [x] No errors in login process
- [x] Logged in username displayed in top right corner
- [x] Message of the Day is displayed
- [x] Message of the Day links are appropriately linked (if applicable)

- [x] "OSC OnDemand" links to "Dashboard" (Should be the same link as in browser)

* Click "Files"
  - [x] "Files" launches in new tab
  - [x] "Files" launches the file manager application
  - [x] The File Manager application places you in your home file directory

* Click "Jobs"
  - [x] Verify "My Jobs" displayed
  - [x] Verify "Active Jobs" displayed

* Click "My Jobs"
  - [x] Verify app opens in same window
  - [x] Verify app opens without errror

* Click "Active Jobs"
  - [x] Verify app opens in same window
  - [x] Verify app opens without errror

* Click "Clusters"
  - [x] Verify "Oakley Shell Access" is displayed
  - [x] Verify "System Status" is displayed

* Click "Apps"
  * Results may vary per user
  - [x] Verify links work appropriately

* Click "Develop" (if available)
  - [ ] Click "Restart Web Server" and reauthenticate
  - [ ] Verify you are redirected back to the dashboard

* Click "Help"
  - [x] Verify "Contact Support" link works appropriately

* Click "Logged in as <user> link"
  - [x] Verify "Change OSC Password" link works
  - [x] Verify Logout function

### Files Test Plan

To begin, click "Files" on the Dashboard to launch the File Explorer app
  - [x] Verify that you are browsing your home directory
  - [x] Verify that no dotfiles are visible (i.e. `.bashrc`)
    * Click the "Show Dotfiles" option at the top of the window
      - [x] Confirm that dotfiles appear/disappear when the box is checked/unchecked
  - [x] Verify that 'owner' and 'mode' of files are not visible
    * Click the "Show Owner/Mode" checkbox
      - [x] Confirm that additional file details appear/disappear when the box is checked/unchecked
    * Click the "Go To ..." button on the left of the top button bar.
      - [x] Ensure that a modal appears that permits you to enter a directory
    * Type `/nfs/gpfs` in the text box and click 'OK'
      - [x] Ensure that the location changes to `/nfs/gpfs/`
    * Click several of the options on the tree view on the left-hand pane.
      - [x] Ensure that the locations displayed change to the proper locations.
    * Click "Home Directory" at the top of the tree view on the left
      - [x] Ensure you are returned to your system home directory.
    * Click the New Dir button at the top of the window and create a new folder with any name.
      - [x] Ensure that a modal appears that permits you to enter the directory name.
      - [x] Ensure that the new folder is created
      - [x] Ensure the new folder is created with permissions `rwx r-x r-x` (toggle "Show Owner/Mode" if necessary)
    * Double-click the new folder that your created.
      - [x] Ensure the new folder opens
    * Click the "New File" button at the top of the page and create a new file with any name.
      - [x] Ensure that a modal appears that permits you to enter the new file name.
    * Enter a name for a new file in the text box and click "OK"
      - [x] Ensure that the new file is created.
      - [x] Ensure that the new file's permissions are `rw- r-- r--` (toggle "Show Owner/Mode" if necessary)

#### Editor test

  * Highlight (click) the newly created file and click the "Edit" button above the panel.
      - [x] Ensure that the Editor opens in a new tab.
      - [x] Ensure that the new file is empty.
      * Add text to the editor window and click "Save". (You could copy and paste this document, for example.)
        - [x] Ensure the save button turns contains a "check" icon temporarily
        - [x] Ensure that save button is disabled after save.
      * Modify the font size via the dropdown.
        - [x] Ensure the font size changes.
      * Modify the mode via the dropdown.
        - [x] Syntax highlighting may or may not change depending on the content. Try several options to confirm that it changes.
      * Modify the theme via the dropdown.
        - [x] Verify that the color styles change
      * Click the "word wrap" checkbox.
        - [x] Confirm that the text wraps/extends (you may need to shrink the window for this)
      * Change some additional text in the document.
        * Click to close the editor tab.
        - [x] Ensure that an alert message pops up asking "Are you sure you want to leave this page?" (Or something similar)
        * Click the option to stay on the page.
      * Click "Save"        
      * Click to close the editor tab.
        - [x] Ensure that no alert popup appears asking if you would like to save.
      * Back in the File Explorer, highlight the file you just edited if it is not already selected.     
      * Click the "View" button above the panel.
        - [x] Ensure that a panel opens that displays the file contents.

  * Back in the file explorer, navigate to the folder you created earlier, if you are not already there. 
    * Click the "Upload" button.
      - [x] Ensure a dialog pops up allowing you to select an upload.
      * Upload a file from your computer to this location (Any file will do)
      - [x] Ensure that a progress indicator appears while the file is uploading.
      - [x] Ensure that the panel refreshes after the upload is complete.
    * Select the file you just uploaded and click the "Rename" button.
      - [x] Ensure you are able to change the file name.
    * Select one of the files in your temporary folder and click "Copy"
      * Navigate to a different path (back one level) and click "Paste"
      - [x] Ensure that a copy of the file is placed in that location.
      * Highlight the pasted file and click the "Delete" button.
      - [x] Ensure the file is deleted
    * Navigate to the temporary folder you were working with.
      * Highlight a single file and click "Download"
      - [x] Ensure your browser prompts to download the file.
      * Back up one folder, select the temporary folder, and click "Download"
      - [x] Ensure your browser prompts you to download the folder name in a `.tar.gz` format.
      * Select the temporary folder and click the "Delete" button.
      - [x] Ensure that a pop-up appears prompting to delete the folder.
      * Click to delete the folder.
      - [x] Ensure the folder is deleted.

### My Jobs

* Click "Jobs" -> "My Jobs" on the dashboard navigation bar
  - [x] Ensure "My Jobs" link exists
  - [x] Ensure "My Jobs" application opens in the same tab
* Click "New From Template" button
  - [x] Ensure "Create a New Job" page loads without error
  - [x] Ensure Templates table is populated with default templates
  - [x] Ensure the first template is selected by default
  - [x] Ensure template data is populated on the right side of the app
* Click a different template in the table
  - [x] Ensure the data on the right panel updates appropriately
* Click "Open Dir" under the template information
  - [x] Ensure cloud commander opens to the appropriate folder in a new tab
* Type something into "Job Name", change "Batch Server", change "Script Name"
  - [x] Ensure all fields are editable
* Click "Reset"
  - [x] Ensure all fields reset to the defaults
* Enter a unique name into "Job Name" and click "Create New Job"
  - [x] Ensure you are returned to index page without error
  - [x] Ensure the job appears in the job list
  - [x] Ensure the job name is the same as the name you entered
* Click and select the newly created job.
* Click "Open Dir" at the top of the "Listing Jobs" panel.
  - [x] Ensure cloud commander opens the job folder in a new tab
  * Close the cloud commander tab
* Click the "Copy Job" button at the top of the "Listing Jobs" panel
  - [x] Ensure the job is duplicated
* Click the "Edit Job" button at the top of the "Listing Jobs" panel
  - [x] Ensure that the Job Edit page opens
  - [x] Ensure that data is populated and matches the selected job.
  * Click "Back"
* Click the green "Submit" button
  - [x] Ensure job status changes to "queued"
* While a job is running, click the "Stop Job" button
  * If the previous job has already completed, duplicate, rerun, and then stop it.
  - [x] Ensure status changes to "Failed"
  - [x] Ensure "Stop Job" button is disabled for the failed job
* Select the failed job and click "Delete Job"
  - [ ] Ensure Job is removed from the list.
* Select a job and click the "Create Template" button. (Create a new job if necessary)
  - [x] Ensure you are redirected to the "New Template" page.
  - [x] Ensure the path of the selected job is in the "Path" field
  * Edit the Name, Default Batch Server, and Notes fields
  * Click "Save"
  - [x] Ensure you are redirected back to the "My Templates" page.
  - [x] Ensure your modifications to title, host, and path are retained.
* Click "Edit Template" in the template row.
  - [x] Ensure the correct template folder opens in the file explorer and files are present.
* Click "Delete Template" in the template row.
  - [x] Ensure the template is deleted and removed from the table.

### Shell

* From the OnDemand Dashboard, click "Clusters" -> "Oakley Shell Access"
  - [x] Ensure that a terminal window opens in a new tab
  - [ ] Ensure that password entry is not required
  - [x] Ensure that the Message of the Day is displayed
  * Type 'pwd'
  - [x] Ensure that you are in your home directory
* If a "Ruby Shell Access" link is available in your dashboard, click it and repeat the above steps.
* Navigate to [https://websvcs08.osc.edu/pun/sys/shell/ssh/oakley/nfs/](https://websvcs08.osc.edu/pun/sys/shell/ssh/oakley/nfs/)
  - [x] Ensure you are placed at a command prompt
  - [x] Ensure that the Message of the Day is NOT displayed
  * Type 'pwd'
  - [x] Ensure you are located in path `/nfs`
* Navigate to [https://websvcs08.osc.edu/pun/sys/shell/ssh/oakley/xvcf/](https://websvcs08.osc.edu/pun/sys/shell/ssh/oakley/xvcf/)
  - [x] Ensure you are placed at a command prompt
  - [x] Ensure that the Message of the Day is displayed
  * Type 'pwd'
  - [x] Ensure you are in your home directory
* Type `module -v`
  - [x] Ensure module app is available
* Type `screen`, then type `screen -ls`
  - [x] Ensure that `screen` is running

### System Status

* From the OnDemand Dashboard, click "Clusters" -> "System Status"
  - [x] Ensure the application loads without error.
  - [x] Ensure Statistics are displayed for Oakley Cluster
  - [x] Ensure Statistics are displayed for Ruby Cluster
* Click the "Oakley Cluster" link in the navigation bar
  - [x] Ensure a page is loaded that includes graphs of Load, CPU, Memory, and Network
  - [x] Ensure all graphs are visible
  * Click each tab for "Hour", "2 Hours", etc.
  - [x] Ensure all graphs appear
* Click the "Ruby Cluster" link in the navigation bar
  - [x] Ensure a page is loaded that includes graphs of Load, CPU, Memory, and Network
  - [x] Ensure all graphs are visible
  * Click each tab for "Hour", "2 Hours", etc.
  - [x] Ensure all graphs appear

### Active Jobs

* Click "Jobs" -> "Active Jobs" on the OnDemand dashboard navigation bar
  - [x] Ensure page loads
  - [x] Ensure "Your Jobs" tab is selected in the upper-right corner.
  - [x] Ensure "Your Group's Jobs (<group>)" contains your primary system group
* Click "All Jobs" Tab
  - [x] Ensure the table populates with the system jobs
  - [x] Ensure the table contains jobs for Oakley and Ruby clusters (You might need to seach or sort)
  * Find a "running" job on the table. Click the black arrow on the left side of the row.
    - [x] Ensure that a panel opens which displays additional information about the job.
    - [x] Ensure that an additional panel or panels appear that contain information about the currently running job.
    * Click the black arrow on the left of the row again.
    - [x] Ensure that the panel collapses and disappears
* For the next tests, you will need to create a running job on the cluster. You can do this however you like, but two simple ways include:
  1. Open a terminal window on Oakley and type/paste the following command: `echo "sleep 240" | qsub -N test -l nodes=1:ppn=12`
  2. Open the "Oakley VDI" app from the Ondemand Dashboard and launch a session.

* When you have jub running on the system, click the tab labeled "Your Jobs" in the top-right of the "Active Jobs" app.
  - [x] Ensure that your job is displayed
  - [x] Ensure that your job is visible in green
* Click "Your Group's Jobs" tab in the top-right of the "Active Jobs" app.
  - [x] Ensure that your job is displayed
  - [x] Ensure that your job is visible in green
  * If other users in your group are running jobs, these will be visible in blue
* Expand your currently running job (create a new one if the job has expired)
  * Click the "Open in File Manager" button
    - [ ] Ensure the File Manager opens in a new tab
    - [ ] Ensure the File Manager opens to the output directory
  * Click the "Open in Terminal" button
    - [ ] Ensure the terminal opens in a new tab
    - [ ] Ensure the terminal opens to the output directory
  * Click the "Delete" button
    - [x] Ensure a dialog box appears asking "Are you sure?"
    * Click "OK"
    - [x] Ensure that a message appears stating that the job was deleted
    - [x] Ensure that the deleted job is no longer visible in the table

### VNC Apps

* From the OnDemand dashboard, click "Apps" -> "Oakley VDI"
  * Under "Create New Session", click "Launch"
    - [x] Ensure a session is successfully created
    - [x] Ensure the session transitions to a "running" state
    * Click "Launch noVNC in New Tab" button.
      - [x] Ensure a new browser tab opens and a desktop is displayed
      - [x] Ensure graphical detail is clear and readable
      * Open a terminal (Applications->System Tools->Terminal) and type "qstat"
        - [x] Ensure no problems
      * Open a web browser (Applications->System Tools-Firefox Web Browser) and perform a google search.
        - [x] Ensure no problems
    * Back in the Oakley VDI app, Click the "Native Client Instructions" tab
      * (WINDOWS) Click the link to download OSC Connect
        - [ ] Ensure the link takes you to a documentation page for OSC Connect
        * Download and run the `OSCConnect.exe` application from the documentation page.
          * Enter your OSC credentials into OSC Connect, click "Remember Me" and close the application.
          * Click the "osc://" link in step 3 of the instructions
          * You may be prompted by your browser that you are making an external protocol request. Click the option to launch the application.
          - [ ] Ensure the application loads based on a click
          - [ ] Ensure the desktop opens in TurboVNC
      * (OSX) Open the "Terminal" app
        * Copy and paste the code into a terminal to open the vnc session
        - [x] Ensure the session connects
        - [x] Ensure the VNC client opens to the remote desktop
    * Back in the Oakley VDI app, Click the "Java Client Instructions" link (Required Java)
      * Click the "Java Client" link and open the file
      - [x] Ensure that the file is downloaded
      - [ ] Ensure that you can connect to a desktop via the JNLP

**Comment by ericfranz** [comment]
@dhudak-osc please update the issue title to reflect which browser you use, whether it is Safari 8 or Safari 9 or later (even the exact version used might be nice). Any problems you run into or annoyances or etc. you can add as separate comments to this issue. Check off the boxes as you go through the steps and verify everything works.

**Comment by dhudak-osc** [comment]
In File Testing:
"Click "Home Directory" at the top of the tree view on the left"
…the Home Directory is almost completely overlapped by the first directory in the list, making selection awkward.

**Comment by dhudak-osc** [comment]
When doing:
Select the failed job and click "Delete Job"
I got a pop up saying "Are you sure?"  I clicked OK, then got a page entitled
We're sorry, but something went wrong (500)

**Comment by dhudak-osc** [comment]
Ensure that password entry is not required
...I was prompted for a password.

**Comment by dhudak-osc** [comment]
Open a terminal window on Oakley and type/paste the following command: echo "sleep 240" | qsub -N test -l nodes=1:ppn=12

I tried to paste that into the ondemand shell, but it would not let me.

**Comment by dhudak-osc** [comment]
Expand your currently running job (create a new one if the job has expired)
Click the "Open in File Manager" button

Gave me
Error -- invalid request: /sys/[object%20Object]
Run 'nginx_stage --help' to see a full list of available command line options.

**Comment by dhudak-osc** [comment]
Ensure that you can connect to a desktop via the JNLP

...did not work as I got this error:
“4560_quick-batch_osc_edu-3.jnlp” can’t be opened because it is from an unidentified developer.

**Comment by ericfranz** [comment]
reviewed all of Dave's comments and wrote up issues for each
